language: java
jdk: openjdk11

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2

script:
  - ./mvnw package -DskipTests=true

after_success:
  - docker build -t paper:latest ./
  - docker tag paper:latest scenecho/paper:latest
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  - docker push scenecho/paper:latest

notifications:
  email:
    recipients:
      - suloginscene@gmail.com
